services:
  app:
    build:
      context: .
    restart: unless-stopped
    image: ghcr.io/onetxpunch/snarkyscan:develop
    expose:
      - 3000
    # ports:
    #   - 80:3000
    env_file:
      - .env.local
